config/routes.rb
Rails.application.routes.draw do

  # User, Shows Routes
  resources :shows do
    get 'search', on: :collection # Searches The Movie Db website
  end
    post 'add_new' => 'add_new', as: 'new_show_by_id'

  resources :actors do
    get 'search', on: :collection # Searches The Movie Db website
  end

  resources :users do
    post 'favorite', on: :member
  end

  resources :favorites, :seasons

  # get 'users/:id/favorites' => 'users#favorites', as: 'favorites'

  # Login and Logout Sessions

  get '/' => 'sessions#new', as: :login
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/models/actor.rb
class Actor < ActiveRecord::Base
  has_and_belongs_to_many :shows

  validates_presence_of :name, :character, :profile_path
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :show
end

app/models/season.rb
class Season < ActiveRecord::Base
    belongs_to :show, dependent: :destroy
end

app/models/show.rb
class Show < ActiveRecord::Base
  has_and_belongs_to_many :actors
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites
  has_many :seasons

  validates_presence_of :title, :genre, :network
  validates_uniqueness_of :title
end

app/models/tvdb.rb
class TVDB

# Searches TV Shows By Title
  def self.search_show_title(tv_info)
    Tmdb::Api.key(ENV["TMDB_API_KEY"])
    find_show = Tmdb::TV.find(tv_info)
    id = find_show[0].id
    tv_show = Tmdb::TV.detail(id)
  end
# Search Actors By TV Show
  def self.search_actors_show(actor_info)
    Tmdb::Api.key(ENV["TMDB_API_KEY"])
    find_show = Tmdb::TV.find(actor_info)
    id = find_show[0].id
    actor_show = Tmdb::TV.cast(id)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :favorites
  has_many :shows, through: :favorites

  has_secure_password

  # need to include relationship for wishlist

  validates_presence_of :username, :first_name, :last_name
  validates_presence_of :email, :birthday, :phone
  validates_uniqueness_of :username, :email

end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController

  def index
    @actors = Actor.all
  end

  def new
    @actor = Actor.new
    @shows = Show.all
  end

  def create
    @actor = Actor.new(actor_params)
    if @actor.save
      redirect_to actor_path(@actor)
    else
      render :new
    end
  end

  def show
    @actor = Actor.find(params[:id])
    @shows = Show.all
  end

  def edit
    @actor = Actor.find(params[:id])
    @shows = Show.all
  end

  def update
    @actor = Actor.find(params[:id])
    if @actor.update(actor_params)
      redirect_to actor_path(@actor)
    else
      render :edit
    end
  end

  def destroy
    @actor = Actor.find(params[:id])
    if @actor.destroy
      redirect_to actors_path
    else
      redirect_to actor_path(@actor)
    end
  end

  def search
    @results = TVDB.search_actors_show(params[:search])
    tmdb_config = Tmdb::Configuration.new
    @poster_sizes = tmdb_config.poster_sizes
    @base_url = tmdb_config.base_url
  end

  private
  def actor_params
    params.require(:actor).permit(:name, :character, :profile_path)
  end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    User.find_by(id:session[:current_user]) if session[:current_user]
  end

  def authenticate
    if !session[:current_user]
      redirect_to login_path
    end
  end

  def authorize
    if session[:current_user] != params[:id].to_i
      redirect_to users_path
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @favorites = Favorite.all
  end

  def new
    @favorite = Favorite.new
    @shows = Show.all
  end

  def create
    @favorite = Favorite.new(fav_params)
    @favorite.user_id = session[:current_user]
    if @favorite.save
      redirect_to favorite_path(@favorite)
    else
      render :new
    end
  end

  def show
    @favorite = Favorite.find(params[:id])
    @user = @favorite.user
  end

  def edit
    @favorite = Favorite.find(params[:id])
    @shows = Show.all
  end

  def update
    @favorite = Favorite.find(params[:id])
    @favorite.update(fav_params)
    if @favorite.save
      redirect_to favorite_path(@favorite)
    else
      render :edit
    end
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    @user = @favorite.user
    if @favorite.destroy
      redirect_to user_path(@user)
    else
      redirect_to favorite_path(@favorite)
    end
  end

  private
  def fav_params
    params.require(:favorite).permit(:user_id, :show_id, :comment, :rating)
  end


end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController

  def index
    @seasons = Season.all
  end

  def new
    @season = Season.new
    @shows = Show.all
  end

  def create
    @season = Season.new(season_params)
    if @season.save
      redirect_to season_path(@season)
    else
      render :new
    end
  end

  def show
    @season = Season.find(params[:id])
  end

  def edit
    @season = Season.find(params[:id])
    @shows = Show.all
  end

  def update
    @season = Season.find(params[:id])
    if @season.update(season_params)
      redirect_to season_path(@season)
    else
      render :edit
    end
  end

  def destroy
    @season = Season.find(params[:id])
    if @season.destroy
      redirect_to seasons_path
    else
      redirect_to season_path(@season)
    end
  end

  private
  def season_params
    params.require(:season).permit(:season_number, :air_date, :poster_path)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user.authenticate(params[:password])
      session[:current_user] = user.id
      redirect_to user_path(user)
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:current_user] = nil
    redirect_to login_path
  end

end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController

  def index
    @shows = Show.all
  end

  def new
    @show = Show.new
  end

  def create
    @show = Show.new(show_params)
    if @show.save
      redirect_to show_path(@show)
    else
      render :new
    end
  end

  def show
    @show = Show.find(params[:id])
  end

  def edit
    @show = Show.find(params[:id])
  end

  def update
    @show = Show.find(params[:id])
    if @show.update(show_params)
      redirect_to show_path(@show)
    else
      render :edit
    end
  end

  def destroy
    @show = Show.find(params[:id])
    if @show.destroy
      redirect_to shows_path
    else
      redirect_to show_path(@show)
    end
  end

  def search
    @results = TVDB.search_show_title(params[:search])
    tmdb_config = Tmdb::Configuration.new
    @poster_sizes = tmdb_config.poster_sizes
    @base_url = tmdb_config.base_url
  end

  private
  def show_params
    params.require(:show).permit(:title, :image_url, :first_air_date, :plot, :genre, :network)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize, only: [:edit, :update, :destroy]

  def index
    # @users = User.all
    redirect_to login_path
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:current_user] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @favorites = @user.favorites
  end

  def edit
    @user = User.find(params[:id])
  end


  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    session[:current_user] = nil
    redirect_to users_path
  end

  private

  def user_params
      params.require(:user).permit(:username, :first_name, :last_name, :password, :password_confirmation, :email, :birthday, :phone)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/actors/_form.html.erb
<% @actor.errors.full_messages do |msg| %>
  <li><%= msg %></li>
<% end %>

<%= form_for @actor do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :character %>
  <%= f.text_field :character %>

  <%= f.label :profile_path %>
  <%= f.text_field :profile_path %>

  <%= f.submit %>

<% end %>

app/views/actors/edit.html.erb
<%= render "form" %>

<%= button_to "Delete", actor_path, method: :delete %>

app/views/actors/index.html.erb
<%= link_to "Add Actors", new_actor_path %>

<p>
  Search Actors by the Title of TV Shows (themoviedb.org):
</p>
<%= form_tag "actors/search", method: :get do %>
  <%= search_field_tag "search" %>
  <%= submit_tag "Search" %>
<% end %>


<ol>
<% @actors.each do |actor| %>
    <li><%= link_to actor.name, actor_path(actor) %></li>
<% end %>
</ol>

app/views/actors/search.html.erb
<h2>Actors By TV Show</h2>
<ol>
<% @results.map do |actor|%>
  <li><strong>Actor:</strong> <%= actor["name"] %></li>
  <p><strong>Character:</strong>
    <%= actor["character"] %>
  </p>
  <% profile_path = actor["profile_path"] %>
  <%= image_tag "#{@base_url}/#{@poster_sizes[3]}#{profile_path}" %>

  <%= form_tag('/actors', method: :post) do |f| %>
    <%= hidden_field_tag 'actor[:name]', actor['name'] %>
    <%= hidden_field_tag 'actor[:character]', actor['character'] %>
    <%= hidden_field_tag 'actor[:profile_path]', actor['profile_path'] %>
    <%= button_to "Add Actor"%>
  <% end %>
<% end %>
</ol>

app/views/actors/show.html.erb
<h2>Name: <%= @actor.name %></h2>
<%= link_to "Edit Actor", edit_actor_path %><br>
<% @actor.shows.each do |show| %>
    Show: <h4><%= link_to show.title, show_path(show) %></h4>
<% end %>
Character Name: <h4><%=@actor.character %></h4>
<%= image_tag @actor.profile_path %>

app/views/favorites/_form.html.erb
<%= form_for @favorite do |f| %>

    <%= f.label :show_id, "Title" %>
    <%= f.select :show_id, options_for_select(@shows.map {|show| [show.title, show.id]}) %>

    <%= f.label :comment  %>
    <%= f.text_area :comment %>

    <%= f.label :rating %>
    <%= f.number_field :rating %>

    <%= f.submit %>
<% end %>

app/views/favorites/edit.html.erb
<h2>Edit Favorite</h2>

<%= render "form" %>

<%= button_to "Delete", favorite_path(@favorite), method: :delete %>

app/views/favorites/index.html.erb
<h2>Favorite TV Shows</h2>
<%= link_to "Add Favorite Show", new_favorite_path %>
<ol>
  <% @favorites.each do |favorite| %>
  <li><%= link_to favorite.show.title, favorite_path(favorite) %> </li>
  <ul>
      <li><%= favorite.comment %></li>
      <li> <%= favorite.rating %> </li>
  </ul>
    <% end %>
</ol

app/views/favorites/new.html.erb
<h2>Add New Favorites</h2>

<%= render "form" %>

app/views/favorites/show.html.erb
<%= link_to "Add Favorite Show", new_favorite_path %>
<%= link_to "Edit Favorite Show", edit_favorite_path %>
<h3><%= link_to @favorite.show.title, show_path(@favorite.show) %></h3>
Comment: <%= @favorite.comment %><br>
Rating: <%= @favorite.rating %><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TvApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1>TV App</h1>
  <p>
  <% if session[:current_user] %>
    Welcome back, <%= User.find(session[:current_user]).first_name %>! |
    <%= link_to "View Profile", user_path(session[:current_user]) %> |
    <%= link_to 'Log Out', logout_path %> |
    <%= link_to 'TV Shows', shows_path %> |
    <%= link_to 'Actors', actors_path %>
  <% else %>
    <%= link_to 'Log In', login_path %> |
    <%= link_to 'Sign Up', new_user_path %> |
    <%= link_to 'TV Shows', shows_path%> |
    <%= link_to 'Actors', actors_path %>
  <% end %>
  </p>

<%= yield %>

</body>
</html>

app/views/seasons/_form.html.erb
<%= form_for @season do |f| %>

  <%= f.label :show_id, "Title" %>
  <%= f.select :show_id, options_for_select(@shows.map {|show| [show.title, show.id]}) %>

  <%= f.label :season_number %>
  <%= f.number_field :season_number %>

  <%= f.label :air_date %>
  <%= f.date_field :air_date %>

  <%= f.label :poster_path %>
  <%= f.text_field :poster_path %>

  <%= f.submit %>

<% end %>

app/views/seasons/edit.html.erb
<%= render "form" %>

app/views/seasons/index.html.erb
<h2>Seasons</h2>
<% @seasons.each do |season| %>
  <%= link_to season.season_number, season_path(season) %>
<% end %>

app/views/seasons/new.html.erb
<%= render "form" %>

app/views/seasons/show.html.erb
<h2>Season Info: </h2>

<p>
  Show: <%= @season.show_id.title %>
</p>
<p>
  Season Number: <%= @season.season_number %>
</p>
<p>
  Air Date: <%= @season.air_date %>
</p>

<p>
  <%= image_tag @season.poster_path %>
</p>

app/views/shows/_form.html.erb
<ol>
  <% @show.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
  <% end %>
</ol>
<%= form_for @show do |f| %>

  <%= f.label :title%>
  <%= f.text_field :title %><br>

  <%= f.label :image_url %>
  <%= f.text_field :image_url %><br>

  <%= f.label :first_air_date %>
  <%= f.date_field :first_air_date %><br>

  <%= f.label :plot %>
  <%= f.text_area :plot %><br>

  <%= f.label :genre %>
  <%= f.text_field :genre %><br>

  <%= f.label :network %>
  <%= f.text_field :network %><br>

  <%= f.submit %><br>

<% end %>

app/views/shows/edit.html.erb
<%= render "form" %>

<%= button_to "Delete", show_path(@show), method: :delete %>

app/views/shows/index.html.erb
<h2>TV Shows</h2>
<%= link_to "Add New TV Show", new_show_path %>
<%= link_to "Add Favorite Shows", new_favorite_path %>
<p>
  Search TV Shows By Title (themoviedb.org):
</p>
<%= form_tag "shows/search", method: :get do %>
  <%= search_field_tag "search" %>
  <%= submit_tag "Search" %>
<% end %>


<ol>
  <% @shows.each do |show| %>
    <li><%= link_to show.title, show_path(show) %> </li>
  <% end %>
</ol>

app/views/shows/search.html.erb
<h2>TV Show</h2>
<%= link_to "Back", shows_path(@shows) %>
<h2>Title: <%= @results.name %></h2>

<% poster_path = @results.poster_path %>
<%= image_tag "#{@base_url}/#{@poster_sizes[3]}#{poster_path}" %>

<p>
  <strong>First Air Date:</strong> <%= @results.first_air_date %>
</p>

<p>
  <strong>Plot:</strong> <%= @results.overview %>
</p>

<p>
  <strong>Genre:</strong> <%= @results.genres[0]["name"] %>
</p>

<p>
  <strong>Network:</strong> <%= @results.networks[0]["name"] %>
</p>

<p>
  <strong>Seasons:</strong>
  <% @results.seasons.map do |season| %>
      <p>
        Season Number: <%= season["season_number"] %>
      </p>
      <p>Air Date:
        <%= season["air_date"] %>
      </p>
      <%= image_tag "#{@base_url}/#{@poster_sizes[3]}#{season["poster_path"]}" %>
  <% end %>
</p>

<%= form_tag('/shows', method: :post) do |f| %>
  <%= hidden_field_tag("show[title]", @results.name) %>
  <%= hidden_field_tag("show[image_url]", "#{@base_url}/#{@poster_sizes[3]}#{@results.poster_path}" )%>
  <%= hidden_field_tag("show[first_air_date]", @results.first_air_date) %>
  <%= hidden_field_tag("show[plot]", @results.overview) %>
  <%= hidden_field_tag("show[genre]", @results.genres[0]["name"]) %>
  <%= hidden_field_tag("show[network]", @results.networks[0]["name"]) %>
  <%= button_to "Add TV Show" %>
<% end %>

app/views/shows/show.html.erb
<h1><%= @show.title %></h1>
<%= link_to "Edit", edit_show_path %><br>
<%= link_to "Add Favorite", new_favorite_path %>
<%= image_tag(@show.image_url) %>
<h3>Air Date: </h3> <%= @show.first_air_date %>
<h3>Genre: </h3> <%= @show.genre %>
<h3>Network: </h3> <%= @show.network %>
<h3>Plot:</h3>
<p>
  <%= @show.plot %>
</p>
<h3>Seasons:</h3>
<ol>
  <% @show.seasons.each do |season| %>
    <li><%= link_to season.season_number, season_path %></li>
    <% end %>
</ol>
<h3>Actors:</h3>
<ol>
  <% @show.actors.each do |actor| %>
    <li><%= link_to actor.name, actor_path(actor) %></li>
  <% end %>
</ol>

app/views/users/_form.html.erb
<% @user.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <br>

  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <br>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <br>

  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br>

  <%= f.label :email  %>
  <%= f.email_field :email %>
  <br>

  <%= f.label :birthday %>
  <%= f.date_field :birthday %>
  <br>

  <%= f.label :phone %>
  <%= f.telephone_field :phone %>

  <%= f.submit %>

<% end %>

app/views/users/edit.html.erb
<h2>Edit User</h2>

<%= render 'form' %>

<%= button_to "Delete", user_path(@user), method: :delete  %>

app/views/users/favorites.html.erb
<h2><%= "#{@user.first_name} #{@user.last_name}" %>'s Favorite Shows</h2>

<ol>
  <% @user.favorites.each do |fav| %>
    <li><%= link_to fav.show.title , show_path(fav.show)%></li>
    <ul>
      <li>Comment: <%= fav.comment %></li>
      <li>Rating: <%= fav.rating %></li>
    </ul>
  <% end %>
</ol>

app/views/users/index.html.erb
<h2>User Index</h2>

<hr>
<% @users.each do |user| %>
    <%= user.username %>
    <%= link_to "#{user.first_name} #{user.last_name}", user_path(user) %>
    <%= user.password_digest %>
    <% if session[:current_user] == user.id %>
      <%= link_to "Edit", edit_user_path(user) %>
      <%= link_to "Remove", user_path(user), method: :delete %>
    <% end %>
    <hr>
<% end %>

app/views/users/new.html.erb
<h2>New User</h2>

<%= render 'form' %>

app/views/users/show.html.erb
<h2><%= @user.first_name %>'s Information</h2>
<%= link_to "Edit", edit_user_path(@user) %>
<h4>Username: <%= @user.username %> </h4>
<h4>First Name: <%= @user.first_name %> </h4>
<h4>Last Name: <%= @user.last_name %> </h4>
<h4>Email Address: <%= @user.email %> </h4>
<h4>Birthday: <%= @user.birthday %></h4>
<h4>Phone Number: <%= @user.phone %></h4>

<h2>Favorite Shows</h2>
<%= link_to "Add Favorite Show", new_favorite_path %>
<ol>
    <% @user.favorites.each do |favorite| %>
      <hr>
      <li>TV Show: <%= link_to favorite.show.title, favorite_path(favorite) %></li>
      <ul>
        <li> Comment: <%= favorite.comment %></li>
        <li> Rating: <%= favorite.rating %></li>
      </ul>
    <% end %>
</ol>